spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Dao.xml
  type-liasesPacage: com/domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #type-aliases-package: com.domain
#  mybatis.config = mybatis 配置文件名称
#  mybatis.mapperLocations = mapper xml 文件地址
#  mybatis.typeAliasesPackage = 实体类包路径
#  mybatis.typeHandlersPackage = type handlers 处理器包路径
#  mybatis.check-config-location = 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
#  mybatis.executorType = 执行模式。默认是 SIMPLE

